server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql//localhost:3306/meal_db
    username: meal_user
    password: meal_pwd
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    #    driver: com.mysql.jdbc.Driver 
        #  h2:
        #    console:
        #      path: /h2
        #      enabled: true
