server:
  port: 8099
spring:
  h2:
    console:
      path: /h2 # jdbc:h2:mem:testdb
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  jackson:
    default-property-inclusion=NON_NULL: